@startuml Chess game flow
start
:Load game data;
while (Want to play game?) is (yes)
    :Select game type;
    :Match player name with piece color;
    while (Is any winning condition met?) is (no)
        :Ask player action;
    endwhile
    ->yes;
    :Display winner;
endwhile
stop
@enduml

