@startuml Chess
class Move
Move : Position initialPosition, finalPosition
Move : Move(initialPosition, finalPosition)

class Position
Position : int x, y
Position : Position(x,y)

interface MoveValidator
MoveValidator : validate(Move move, Board board):boolean

' Piece Handler
interface Board
Board : getpieceInPosition(Position position):Optional<Piece>
Board : doesPositionExist(Position position):boolean
Board : removePieceInPosition(Position position):Board
Board : setPieceInPosition(Position position):Board

interface Piece
Piece : getName():String
Piece : value():int


@enduml